stages:
  - build

build-and-push:
  stage: build
  image: docker:24
  services:
    - docker:24-dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  only:
    - main
  before_script:
    - echo "$DOCKERHUB_TOKEN" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
  script:
    # Build & Push 爬蟲（試題1）
    - docker build -t layla8537/ris-crawler:latest ./試題1
    - docker push layla8537/ris-crawler:latest
    # Build & Push API（試題2）
    - docker build -t layla8537/ris-api:latest ./試題2
    - docker push layla8537/ris-api:latest
  after_script:
    - docker logout
